/** Definiciones de mantenedores Fleet (modelo PDF + Wisetrack). */

/** Patente y Wisetrack solo para el SELECT. El filtro usa id interno ya resuelto, no LIKE de este join. */
const vehicleReadJoin = {
  alias: 'veh',
  table: 'vehicles',
  on: 'veh.id = t.vehicle_id',
  type: 'left',
  fields: [
    { field: 'plate', column: 'plate', searchable: false },
    { field: 'wisetrack_vehicle_id', column: 'wisetrack_vehicle_id', searchable: false },
  ],
}

export const FLEET_ENTITIES = [
  // --- Maestros ---
  {
    routeSlug: 'vehicles',
    auditEntity: 'Vehicle',
    table: 'vehicles',
    displayField: 'plate',
    softDisable: null,
    defaultSort: { by: 'vehicle_number', dir: 'asc' },
    joins: [
      {
        alias: 'div',
        table: 'divisions',
        on: 'div.external_id = t.division_id',
        fields: [{ field: 'division', column: 'name', searchable: true }],
      },
      {
        alias: 'dist',
        table: 'districts',
        on: 'dist.external_id = t.district_id',
        fields: [{ field: 'district', column: 'name', searchable: true }],
      },
      {
        alias: 'grp',
        table: 'org_groups',
        on: 'grp.external_id = t.group_id',
        fields: [{ field: 'group_name', column: 'name', searchable: true }],
      },
      {
        alias: 'cc',
        table: 'cost_centers',
        on: 'cc.external_id = t.cost_center_id',
        fields: [{ field: 'cost_center', column: 'name', searchable: true }],
      },
      {
        alias: 'st',
        table: 'stations',
        on: 'st.external_id = t.station_id',
        fields: [{ field: 'station', column: 'name', searchable: true }],
      },
    ],
    fields: [
      { field: 'vehicle_number', type: 'string', required: true, searchable: true },
      { field: 'plate', type: 'string', required: true, searchable: true },
      { field: 'vin', type: 'string', required: false, searchable: true },
      { field: 'make', type: 'string', required: false, searchable: true },
      { field: 'model', type: 'string', required: false, searchable: true },
      { field: 'status', type: 'string', required: false, searchable: true },
      { field: 'initial_odometer', type: 'int', required: false },
      { field: 'wisetrack_vehicle_id', type: 'string', required: false, searchable: true },
      { field: 'traumasoft_vehicle_id', type: 'int', required: false, readOnly: true },
      { field: 'division_id', type: 'int', required: false, readOnly: true },
      { field: 'district_id', type: 'int', required: false, readOnly: true },
      { field: 'group_id', type: 'int', required: false, readOnly: true },
      { field: 'cost_center_id', type: 'int', required: false, readOnly: true },
      { field: 'station_id', type: 'int', required: false, readOnly: true },
    ],
  },
  {
    routeSlug: 'persons',
    auditEntity: 'Person',
    table: 'persons',
    displayField: 'name',
    softDisable: { column: 'is_active', activeValue: 1, inactiveValue: 0 },
    fields: [
      { field: 'rut', type: 'string', required: true, searchable: true },
      { field: 'name', type: 'string', required: true, searchable: true },
      { field: 'category', type: 'string', required: false, searchable: true },
      { field: 'is_active', type: 'bit', required: false },
    ],
  },

  // --- Kilometraje ---
  {
    routeSlug: 'gps-minute-pings',
    auditEntity: 'GpsMinutePing',
    table: 'gps_minute_pings',
    displayField: 'vehicle_id',
    readOnly: false,
    softDisable: null,
    defaultSort: { by: 'ts', dir: 'desc' },
    dateFilter: { field: 'ts', type: 'datetimeoffset' },
    joins: [vehicleReadJoin],
    fields: [
      { field: 'vehicle_id', type: 'bigint', required: true },
      { field: 'ts', type: 'datetimeoffset', required: true },
      { field: 'odometer_km', type: 'decimal', required: false },
      { field: 'latitude', type: 'decimal', required: false },
      { field: 'longitude', type: 'decimal', required: false },
      { field: 'speed_kmh', type: 'smallint', required: false },
      { field: 'ignition_on', type: 'bit', required: false },
    ],
  },
  {
    routeSlug: 'gps-daily-km',
    auditEntity: 'GpsDailyKm',
    table: 'gps_daily_km',
    softDisable: null,
    defaultSort: { by: 'reading_date', dir: 'desc' },
    dateFilter: { field: 'reading_date', type: 'date' },
    joins: [vehicleReadJoin],
    fields: [
      { field: 'vehicle_id', type: 'bigint', required: true },
      { field: 'reading_date', type: 'date', required: true },
      { field: 'km_raw', type: 'decimal', required: false },
      { field: 'first_odometer_km', type: 'decimal', required: false },
      { field: 'last_odometer_km', type: 'decimal', required: false },
      { field: 'ping_count', type: 'int', required: false },
      { field: 'has_anomaly', type: 'bit', required: false },
      { field: 'is_consistent', type: 'bit', required: false },
    ],
  },
  {
    routeSlug: 'physical-readings',
    auditEntity: 'PhysicalReading',
    table: 'physical_readings',
    softDisable: null,
    dateFilter: { field: 'reading_date', type: 'date' },
    joins: [vehicleReadJoin],
    fields: [
      { field: 'vehicle_id', type: 'bigint', required: true },
      { field: 'recorded_by_person_id', type: 'bigint', required: false },
      { field: 'reading_date', type: 'date', required: true },
      { field: 'odometer_km', type: 'int', required: true },
      { field: 'status', type: 'string', required: false, searchable: true },
    ],
  },
  {
    routeSlug: 'reconciliation-periods',
    auditEntity: 'ReconciliationPeriod',
    table: 'reconciliation_periods',
    softDisable: null,
    joins: [vehicleReadJoin],
    fields: [
      { field: 'vehicle_id', type: 'bigint', required: true },
      { field: 'start_reading_id', type: 'bigint', required: false },
      { field: 'end_reading_id', type: 'bigint', required: false },
      { field: 'start_date', type: 'date', required: false },
      { field: 'end_date', type: 'date', required: false },
      { field: 'gps_total_km', type: 'decimal', required: false },
      { field: 'correction_factor', type: 'decimal', required: false },
      { field: 'status', type: 'string', required: false, searchable: true },
    ],
  },
  {
    routeSlug: 'odometer-daily',
    auditEntity: 'OdometerDaily',
    table: 'odometer_daily',
    softDisable: null,
    defaultSort: { by: 'reading_date', dir: 'desc' },
    dateFilter: { field: 'reading_date', type: 'date' },
    joins: [vehicleReadJoin],
    fields: [
      { field: 'vehicle_id', type: 'bigint', required: true },
      { field: 'reading_date', type: 'date', required: true },
      { field: 'km_adjusted', type: 'decimal', required: false },
      { field: 'odometer_eod', type: 'decimal', required: false },
      { field: 'period_id', type: 'bigint', required: false },
      { field: 'is_final', type: 'bit', required: false },
    ],
  },

  // --- Combustible ---
  {
    routeSlug: 'fuel-cards',
    auditEntity: 'FuelCard',
    table: 'fuel_cards',
    displayField: 'card_number',
    softDisable: null,
    joins: [vehicleReadJoin],
    fields: [
      { field: 'vehicle_id', type: 'bigint', required: true },
      { field: 'card_number', type: 'string', required: true, searchable: true },
      { field: 'valid_from', type: 'date', required: false },
      { field: 'valid_to', type: 'date', required: false },
    ],
  },
  {
    routeSlug: 'fuel-stations',
    auditEntity: 'FuelStation',
    table: 'fuel_stations',
    displayField: 'direccion',
    softDisable: null,
    fields: [
      { field: 'comuna', type: 'string', required: false, searchable: true },
      { field: 'direccion', type: 'string', required: false, searchable: true },
      { field: 'region', type: 'string', required: false, searchable: true },
    ],
  },
  {
    routeSlug: 'fuel-transactions',
    auditEntity: 'FuelTransaction',
    table: 'fuel_transactions',
    displayField: 'comprobante',
    softDisable: null,
    joins: [vehicleReadJoin],
    fields: [
      { field: 'vehicle_id', type: 'bigint', required: true },
      { field: 'card_id', type: 'bigint', required: false },
      { field: 'station_id', type: 'bigint', required: false },
      { field: 'driver_person_id', type: 'bigint', required: false },
      { field: 'transaction_ts', type: 'datetimeoffset', required: true },
      { field: 'comprobante', type: 'string', required: false, searchable: true },
      { field: 'product', type: 'string', required: false, searchable: true },
      { field: 'volume_liters', type: 'decimal', required: false },
      { field: 'total_amount', type: 'decimal', required: false },
      { field: 'odometer_raw', type: 'int', required: false },
      { field: 'odometer_clean', type: 'int', required: false },
      { field: 'discarded', type: 'bit', required: false },
    ],
  },

  // --- Operacional ---
  {
    routeSlug: 'ordering-facilities',
    auditEntity: 'OrderingFacility',
    table: 'ordering_facilities',
    displayField: 'name',
    softDisable: { column: 'is_active', activeValue: 1, inactiveValue: 0 },
    fields: [
      { field: 'external_id', type: 'int', required: false, searchable: true },
      { field: 'name', type: 'string', required: true, searchable: true },
      { field: 'type', type: 'string', required: false, searchable: true },
      { field: 'is_active', type: 'bit', required: false },
    ],
  },
  {
    routeSlug: 'placeholder-patients',
    auditEntity: 'PlaceholderPatient',
    table: 'placeholder_patients',
    displayField: 'placeholder_name',
    softDisable: { column: 'is_active', activeValue: 1, inactiveValue: 0 },
    fields: [
      { field: 'rut', type: 'string', required: false, searchable: true },
      { field: 'los', type: 'string', required: false, searchable: true },
      { field: 'placeholder_name', type: 'string', required: false, searchable: true },
      { field: 'is_patient_attention', type: 'bit', required: false },
      { field: 'is_productive_use', type: 'bit', required: false },
      { field: 'nature', type: 'string', required: false, searchable: true },
      { field: 'is_active', type: 'bit', required: false },
    ],
  },
  {
    routeSlug: 'placeholder-vehicles',
    auditEntity: 'PlaceholderVehicle',
    table: 'placeholder_vehicles',
    softDisable: { column: 'is_active', activeValue: 1, inactiveValue: 0 },
    fields: [
      { field: 'movil_number', type: 'int', required: true, searchable: true },
      { field: 'purpose', type: 'string', required: false, searchable: true },
      { field: 'is_active', type: 'bit', required: false },
    ],
  },
  {
    routeSlug: 'shifts',
    auditEntity: 'Shift',
    table: 'shifts',
    displayField: 'name_template',
    softDisable: null,
    fields: [
      { field: 'shift_id', type: 'bigint', required: true },
      { field: 'unit_name', type: 'string', required: false, searchable: true },
      { field: 'puesto_trabajo', type: 'string', required: false, searchable: true },
      { field: 'vehicle_category', type: 'string', required: false, searchable: true },
      { field: 'name_template', type: 'string', required: false, searchable: true },
    ],
  },
  {
    routeSlug: 'shift-persons',
    auditEntity: 'ShiftPerson',
    table: 'shift_persons',
    softDisable: null,
    fields: [
      { field: 'shift_fk', type: 'bigint', required: true },
      { field: 'person_id', type: 'bigint', required: true },
      { field: 'date_line', type: 'date', required: false },
      { field: 'start_time', type: 'datetimeoffset', required: false },
      { field: 'end_time', type: 'datetimeoffset', required: false },
      { field: 'start_actual', type: 'datetimeoffset', required: false },
      { field: 'end_actual', type: 'datetimeoffset', required: false },
    ],
  },
  {
    routeSlug: 'runs',
    auditEntity: 'Run',
    table: 'runs',
    softDisable: null,
    fields: [
      { field: 'run_number', type: 'bigint', required: true },
      { field: 'ordering_facility_id', type: 'bigint', required: false },
      { field: 'placeholder_patient_id', type: 'bigint', required: false },
      { field: 'turno_code', type: 'string', required: false, searchable: true },
      { field: 'tipo_atencion', type: 'string', required: false, searchable: true },
      { field: 'los', type: 'string', required: false, searchable: true },
      { field: 'zona', type: 'string', required: false, searchable: true },
      { field: 'vehiculo_category', type: 'string', required: false, searchable: true },
      { field: 'business_unit', type: 'string', required: false, searchable: true },
      { field: 'is_patient_attention', type: 'bit', required: false },
      { field: 'is_productive_use', type: 'bit', required: false },
    ],
  },
  {
    routeSlug: 'run-legs',
    auditEntity: 'RunLeg',
    table: 'run_legs',
    softDisable: null,
    joins: [vehicleReadJoin],
    fields: [
      { field: 'run_id', type: 'bigint', required: true },
      { field: 'leg_id', type: 'bigint', required: true },
      { field: 'vehicle_id', type: 'bigint', required: false },
      { field: 'placeholder_vehicle_id', type: 'bigint', required: false },
      { field: 'movil_text', type: 'string', required: false, searchable: true },
      { field: 'is_third_party', type: 'bit', required: false },
      { field: 'last_status', type: 'string', required: false, searchable: true },
      { field: 'assigned_time', type: 'datetimeoffset', required: false },
      { field: 'enroute_time', type: 'datetimeoffset', required: false },
      { field: 'at_scene_time', type: 'datetimeoffset', required: false },
      { field: 'transporting_time', type: 'datetimeoffset', required: false },
      { field: 'at_destination_time', type: 'datetimeoffset', required: false },
      { field: 'clear_time', type: 'datetimeoffset', required: false },
    ],
  },

  // --- Integraciones (solo lectura en UI; create vía jobs) ---
  {
    routeSlug: 'wisetrack-ingestion-log',
    auditEntity: 'WisetrackIngestionLog',
    table: 'wisetrack_ingestion_log',
    displayField: 'batch_id',
    readOnly: true,
    softDisable: null,
    fields: [
      { field: 'batch_id', type: 'string', searchable: true, readOnly: true },
      { field: 'started_at', type: 'datetimeoffset', readOnly: true },
      { field: 'completed_at', type: 'datetimeoffset', readOnly: true },
      { field: 'period_from', type: 'datetimeoffset', readOnly: true },
      { field: 'period_to', type: 'datetimeoffset', readOnly: true },
      { field: 'n_vehicles_expected', type: 'int', readOnly: true },
      { field: 'n_vehicles_reporting', type: 'int', readOnly: true },
      { field: 'n_pings_received', type: 'bigint', readOnly: true },
      { field: 'n_pings_inserted', type: 'bigint', readOnly: true },
      { field: 'n_pings_duplicated', type: 'bigint', readOnly: true },
      { field: 'n_pings_rejected', type: 'bigint', readOnly: true },
      { field: 'status', type: 'string', searchable: true, readOnly: true },
      { field: 'error_details', type: 'string', readOnly: true },
    ],
  },
  {
    routeSlug: 'wisetrack-rejected-pings',
    auditEntity: 'WisetrackRejectedPing',
    table: 'wisetrack_rejected_pings',
    readOnly: true,
    softDisable: null,
    fields: [
      { field: 'batch_id', type: 'string', searchable: true, readOnly: true },
      { field: 'wisetrack_vehicle_id', type: 'string', searchable: true, readOnly: true },
      { field: 'plate', type: 'string', searchable: true, readOnly: true },
      { field: 'ping_ts', type: 'datetimeoffset', readOnly: true },
      { field: 'reason', type: 'string', searchable: true, readOnly: true },
      { field: 'raw_payload', type: 'string', readOnly: true },
      { field: 'ingested_at', type: 'datetimeoffset', readOnly: true },
    ],
  },
  {
    routeSlug: 'wisetrack-api-tokens',
    auditEntity: 'WisetrackApiToken',
    table: 'wisetrack_api_tokens',
    displayField: 'status',
    readOnly: true,
    softDisable: { column: 'is_active', activeValue: 1, inactiveValue: 0 },
    fields: [
      { field: 'config_id', type: 'bigint', readOnly: true },
      { field: 'token_type', type: 'string', searchable: true, readOnly: true },
      { field: 'expires_at', type: 'datetimeoffset', readOnly: true },
      { field: 'obtained_at', type: 'datetimeoffset', readOnly: true },
      { field: 'is_active', type: 'bit', readOnly: true },
      { field: 'status', type: 'string', searchable: true, readOnly: true },
      { field: 'source', type: 'string', searchable: true, readOnly: true },
      { field: 'notes', type: 'string', readOnly: true },
    ],
  },
]
